name: Tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: [8.3, 8.2, 8.1]
                illuminate: [10.*, 11.*]
                dependency-version: [prefer-lowest, prefer-stable]
                exclude:
                    - php: 8.1
                      illuminate: 11.*

        name: P${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }} - I ${{ matrix.illuminate }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Install Puppeteer
                run: npm install puppeteer

            -   name: Install and start test server
                run: |
                    cd tests/server
                    npm install
                    (node server.js &) || /bin/true

            -   name: Wait for server bootup
                run: sleep 5

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                    coverage: none

            -   name: Install dependencies
                run: |
                    composer require "laravel/framework:${{ matrix.illuminate }}" --no-interaction --no-update
                    composer update --${{ matrix.dependency-version }} --no-interaction --prefer-source

            -   name: Execute tests
                run: vendor/bin/pest
